# Generated by Django 3.1.4 on 2021-03-05 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('team', models.CharField(max_length=100)),
                ('reward', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('ACMer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('author_id', models.IntegerField(default=0)),
                ('desc', models.TextField(default='', max_length=327)),
                ('content', models.TextField(max_length=32765)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=20)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=1000)),
                ('filename', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CountDownSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('sign', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Href',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=12321)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=1000)),
                ('uploader', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('memory', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('file', models.TextField(max_length=1000)),
                ('uid', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('uid', models.TextField(max_length=1000)),
                ('filename', models.TextField(max_length=1000)),
                ('nickname', models.CharField(default='HNUSTACMer', max_length=100)),
                ('pwd', models.CharField(default='123456789', max_length=120)),
                ('follow', models.IntegerField(default=0)),
                ('articles', models.IntegerField(default=0)),
                ('note', models.CharField(default='让我们红橙作伴，活的潇潇洒洒', max_length=100)),
                ('root', models.IntegerField(default=0)),
            ],
        ),
    ]
